// src/app/Layouts/Title-Bar.tsx
"use client";

export default function TitleBar() {
  return (
    <div className="Title-Bar">
      <div className="options">{/* <logo-blue /> */}</div>
      {/* <button className="search">
        <Search_Icon  />
        Search
      </button> */}
      <div className="actions"></div>
    </div>
  );
}

// src/renderer/src/layout/TitleBar.svelte
<script lang="ts">
  import IconX from "../assets/Icon-X.svelte";
  import IconMinus from "../assets/Icon-Minus.svelte";
  import IconSquare from "../assets/Icon-Square.svelte";
  import LogoBlue from "../assets/logo-Blue.svelte";
  import IconSearch from "../assets/Icon-Search.svelte";
</script>

<div class="title-bar">
  <div class="options">
    <LogoBlue />
    <button>New</button>
  </div>
  <button class="search"><IconSearch /> Search</button>
  <div class="actions">
    <IconMinus />
    <IconSquare />
    <IconX />
  </div>
</div>
