// app/Layout/Title-Bar.tsx
"use client"
import Button from "../Components/Button"

interface PropsType extends React.HTMLAttributes<HTMLDivElement> {}
export default function TitleBar(props: PropsType) {
  return (
    <div className="Title-Bar">
      <div className="options">
        {/* <logo-blue /> */}
        <Button>New</Button>
        <Button>Clear</Button>
      </div>
      <button className="search">
        {/* <icon-search /> */}
        Search
      </button>
      <div className="actions">
        {/* <icon-minus /> */}
        {/* <icon-square /> */}
        {/* <icon-x /> */}
      </div>
    </div>
  )
}

// src/renderer/src/layout/TitleBar.svelte
<script lang="ts">
  import IconX from "../assets/Icon-X.svelte";
  import IconMinus from "../assets/Icon-Minus.svelte";
  import IconSquare from "../assets/Icon-Square.svelte";
  import LogoBlue from "../assets/logo-Blue.svelte";
  import IconSearch from "../assets/Icon-Search.svelte";
</script>

<div class="title-bar">
  <div class="options">
    <LogoBlue />
    <button>New</button>
  </div>
  <button class="search"><IconSearch /> Search</button>
  <div class="actions">
    <IconMinus />
    <IconSquare />
    <IconX />
  </div>
</div>
